Add leavesMap and fix broken tests on `identity-vanchor` and `vanchorForest`
webb-tools/protocol-solidity pull request #247
Opened 2023-02-07 21:17 UTC by semaraugusto

* Fixing tests for identity-vanchor and vanchor-forest
* Add leavesMap parameter to transaction in both classes

2023-02-13 12:05 UTC, drewstone commented
@shekohex possibly this PR fixed some issues you're having. We should review and merge asap. CC @saiakilesh 

There does seem to be a lot of commented out code here still @semaraugusto. Would be good to clean it up and make this PR ready to merge. It would also be good to write some cross chain tests for these anchors to ensure the changes made here are actually working for the intended functionality.

2023-02-17 09:00 UTC, drewstone commented
Merge conflicts here still, any update?

2023-02-17 09:26 UTC, semaraugusto commented
I'm finishing the cross-chain tests for the identity-vanchor. One can be part of a semaphore group on chain A and prove membership (which allows him to transact) on chainB. The cross-chain withdraw test is still failing. I'll do a clean up and merge when I get it working

2023-02-17 23:13 UTC, saiakilesh approved these changes

2023-02-18 09:38 UTC, drewstone requested changes
LG, @semaraugusto @saiakilesh can we make sure in future reviews that you guys are also checking for code style and documentation? This PR took a ~week and there's still commented code that is left here and not a meaningful improvement of documentation in the code. We can do better here

2023-02-18 09:38 UTC, drewstone commented on packages/contracts/test/identityVAnchor/identityVAnchor.test.ts
> +      // const updateEdgeTx = await semaphore.updateEdge(groupId.toNumber(), ganacheGroup.root.toString(), 1, chainID2)
Are these comments needed?

2023-02-18 09:38 UTC, drewstone commented on packages/contracts/test/identityVAnchor/identityVAnchor.test.ts
> +      // const updateEdgeReceipt = await updateEdgeTx.wait()
Here too?

2023-02-18 09:38 UTC, drewstone commented on packages/contracts/test/identityVAnchor/identityVAnchor.test.ts
> +      // let john_addmember_tx = await ganacheSemaphore.contract
Is this needed?

2023-02-18 09:38 UTC, drewstone commented on packages/contracts/test/identityVAnchor/identityVAnchor.test.ts
> +      // const tx2 = await ganacheSemaphore.addMember(groupId.toNumber(), group.root.toString(), 2, chainID);
Can this be removed?

2023-02-18 09:38 UTC, drewstone commented on packages/contracts/test/identityVAnchor/identityVAnchor.test.ts
> +      // const receipt = await alice_addmember_tx.wait();
Can this be removed?

2023-02-18 09:38 UTC, drewstone commented on packages/anchors/src/VAnchorForest.ts
> +      // const forestElements = leavesMap[treeChainId]
Can this be removed?

2023-02-18 09:38 UTC, drewstone commented on packages/anchors/src/Common.ts
> +    // inputs = await this.padUtxos(inputs, 16);
Can this be removed?

2023-02-18 09:38 UTC, drewstone commented on packages/anchors/src/Common.ts
> +    // this.validateInputs(inputs);
Can this be removed?

2023-02-19 09:12 UTC, merged