[feat] Add Refund logic in place
webb-tools/protocol-solidity pull request #251
Opened 2023-02-10 16:56 UTC by shekohex

### Overview

The Refund process works like the following:

1. User requests some native tokens to be sent to the recipient along with the wrapped (or unwrapped) tokens.
2. The relayer validates this logic and sends the requested amount as a native token value to the smart contract.
3. we process the refund if and only if the value of the refund requested is greater than zero and equal to `msg.value` sent to the smart contract from the relayer.
4. Once processed, the value is sent to the recipient, if that failed we return it to the relayer or revert.

### Task Checklist

- [x] Initial Implementation
- [x] Documentation
- [ ] Add Happy Path tests
- [ ] Add negative tests.

2023-02-10 16:58 UTC, shekohex commented
Hey @drewstone or @saiakilesh Could you help writing some tests for that? If not, could you please point me where to write these tests, and what is the workflow for running them?

2023-02-10 17:02 UTC, drewstone commented
I would write them alongside the regular vanchor tests. You’ll want to
build the classes so that they have this logic of course.

You can create a separate file for the refund tests to keep it tidy. We
just need to:
1. Do a deposit
2. Relay a withdrawal with a non zero refund to a “relayer” (simulate this
ofc). The relayer will need to submit the withdrawal tx with a msg.value
that matches the refund. Then we should verify both the withdrawn token
balance of the recipient and the native balance of the recipient to show
the refund succeeded. Negative tests would be the opposite (messing with
values)

On Fri, Feb 10, 2023 at 9:58 AM shekohex ***@***.***> wrote:

> Hey @drewstone <https://github.com/drewstone> or @saiakilesh
> <https://github.com/saiakilesh> Could you help writing some tests for
> that? If not, could you please point me where to write these tests, and
> what is the workflow for running them?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/webb-tools/protocol-solidity/pull/251#issuecomment-1426085959>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADELLF3KOAXXIY3AZ3Y5HTLWWZXU7ANCNFSM6AAAAAAUYAQMCY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-10 22:09 UTC, saiakilesh commented
@drewstone @shekohex Added some tests. The only change I made to Shady's contract work is that we should only refund during a withdraw (aka `extAmount < 0`).

2023-02-13 11:45 UTC, shekohex commented
I'm working on fixing these failing tests right now, but for some reason, Locally only one test fails while on CI there are two of them!

2023-02-13 12:08 UTC, drewstone requested changes
LG overall, would be interested to hear you thoughts on tests.

2023-02-13 12:08 UTC, drewstone commented on packages/contracts/test/vanchor/vanchor.test.ts
> +      // Alice deposits into tornado pool
Fix comments. Remove Tornado

2023-02-13 13:05 UTC, shekohex commented on packages/contracts/test/vanchor/vanchor.test.ts
> +    it('should not refund upon internal transfer', async () => {
I guess the main reason is that the `extAmount` here would be Zero. @saiakilesh any idea why we do not need to want to allow this?

2023-02-13 14:13 UTC, saiakilesh commented on packages/contracts/test/vanchor/vanchor.test.ts
> +    it('should not refund upon internal transfer', async () => {
@drewstone 

This is specifically the case where `extAmount` is 0. So no funds are deposited/withdrawn, only commitments are added to the Merkle tree and nullifiers are stored on the smart contract. In this case, I thought there is no need for a refund?

2023-02-14 07:31 UTC, drewstone commented
> @drewstone @shekohex Added some tests. The only change I made to Shady's contract work is that we should only refund during a withdraw (aka `extAmount < 0`).

Let's chat today about this, want to make sure the user story makes sense entirely.

2023-02-14 07:31 UTC, merged