signing with nonce
webb-tools/protocol-solidity pull request #96
Opened 2022-01-03 21:28 UTC by saiakilesh

2022-01-03 21:43 UTC, drewstone requested changes
Can we make sure to hound more nonce updates for all proposals necessary including this one?

2022-01-03 21:43 UTC, drewstone commented on contracts/utils/Governable.sol
> +        require(nonce <= refreshNonce + 1, "Nonce must increment by 1");
We need to add checks that nonce doesn't increase tremendously (causing overflow attack).

2022-01-03 21:44 UTC, drewstone commented on contracts/utils/Governable.sol
> +        require(nonce <= refreshNonce + 1, "Nonce must increment by 1");
Oops I had it backwards. This looks good.

2022-01-03 21:51 UTC, saiakilesh commented
> Can we make sure to hound more nonce updates for all proposals necessary including this one?

What does hound more nonce updates mean? I didn't understand.

2022-01-03 21:52 UTC, drewstone commented
Bound*

2022-01-03 22:00 UTC, saiakilesh commented
> Bound*

Ah ok cool.

2022-01-04 14:44 UTC, drewstone approved these changes

2022-01-04 14:44 UTC, merged